services:
  postgres:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_DB: musicmentor
      POSTGRES_USER: musmentor
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - musicmentor_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U musmentor -d musicmentor"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=musicmentor;Username=musmentor;Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: MusicMentor.Api
      Jwt__Audience: MusicMentor.Client
      Jwt__SecretKey: ${JWT_KEY}
      Jwt__AccessTokenMinutes: 60

    ports:
      - "8082:8080"
    # expose:
    #   - "8080"

    networks:
      - internal
      - proxy

  frontend:
    build:
      context: ./frontend

    restart: unless-stopped

    depends_on:
      - api

    ports:
      - "3000:3000"
    # expose:
    #   - "3000"

    networks:
      - proxy

networks:
  internal:
  proxy:
    external: true

volumes:
  musicmentor_pgdata: